name: PHP Composer

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
    name: PHP ${{ matrix.php }} Tests
    steps:
    - name: Locally, Install Deps
      run: |
        add-apt-repository -y ppa:apt-fast/stable
        apt update
        apt install -y apt-fast bc composer
      if: github.actor == 'nektos/act'

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: nanasess/setup-php@v3
      with:
        php-version: ${{ matrix.php }}

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php${{ matrix.php }}-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run static checks
      run: vendor/bin/psalm

    - name: Run test suite
      run: vendor/bin/phpunit
